<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div class="box-account box-dashboard">
    <div class="box-head box-title">
        <h3><?php echo $this->__('Address Book') ?></h3>
        <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
    </div>
    <div class="box-content">
        <div class="item-address">
            <h4><?php echo $this->__('Default Billing Address') ?></h4>
            <address>
                <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
            </address>
            <p>
                <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </p>
        </div>
        <div class="item-address">
            <h4><?php echo $this->__('Default Shipping Address') ?></h4>
            <address>
                <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
            </address>
            <p>
                <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
            </p>
        </div>
    </div>
</div>
