<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div class="box-account box-dashboard">
    <div class="box-head box-title">
        <h3><?php echo $this->__('Contact Information') ?></h3>
        <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
    </div>
    <div class="box-content">
        <p>
            <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
            <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>
</div>
<?php if( $this->isNewsletterEnabled() ): ?>
    <div class="box-account box-dashboard">
        <div class="box-head box-title">
            <h3><?php echo $this->__('Newsletters') ?></h3>
            <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        <div class="box-content">
            <p>
                <?php if( $this->getIsSubscribed() ): ?>
                    <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                <?php else: ?>
                    <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                <?php endif; ?>
            </p>
        </div>
    </div>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
<?php endif; ?>
