<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$_h = $this->helper('integento_catalog');
$_collectionSize = $_productCollection->count();

if($_collectionSize < 1): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
<div class="category-products">
    <?php
    echo $this->getToolbarHtml();
    echo '<ul class="products-grid ig-products-list">';
    foreach ($_productCollection as $_product):
        echo '<li>'.$_h->getProductHTML($_product).'</li>';
    endforeach;
    echo '</ul>';
    ?>
</div>
<?php endif;
