<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1 class="main-title"><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
</div>
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
    <ul class="cssc-form cssc-form--mage float-form">
        <li class="box">
            <label for="name" class="required"><?php echo Mage::helper('contacts')->__('Name') ?> <em>*</em></label>
            <div class="input-box">
                <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
            </div>
        </li>
        <li class="box">
            <label for="email" class="required"><?php echo Mage::helper('contacts')->__('Email') ?> <em>*</em></label>
            <div class="input-box">
                <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
            </div>
        </li>
        <li class="box">
            <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
            <div class="input-box">
                <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
            </div>
        </li>
        <li class="box">
            <label for="comment" class="required"><?php echo Mage::helper('contacts')->__('Comment') ?> <em>*</em></label>
            <div class="input-box">
                <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
            </div>
        </li>
        <li class="box submit-box">
            <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
            <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="cssc-button cssc-button--mage"><?php echo Mage::helper('contacts')->__('Submit') ?></button>
        </li>
    </ul>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
