<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

$_product = $this->getProduct();
$buttonTitle = $this->__('Add to Cart');
if($_product->isSaleable()):
    if(!$_product->isGrouped()):
    $_itemQty = $this->getProductDefaultQty() * 1;
    $_qtyMax = min(10, max($_product->getStockItem()->getMaxSaleQty(), $_itemQty));
    if($_qtyMax > 0):
    ?>
    <div class="add-to-qty">
        <label for="qty"><?php echo $this->__('Qty:') ?></label>
        <select name="qty" id="qty" title="<?php echo $this->__('Qty') ?>" class=" qty">
        <?php for ($i = 1; $i <= $_qtyMax; $i++) { ?>
            <option <?php echo ($i == $_itemQty ? 'selected="selected"' : '') ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
        <?php } ?>
        </select>
    </div>
    <?php endif; ?>
    <?php endif; ?>

    <div class="add-to-cart">
        <button type="button" title="<?php echo $buttonTitle ?>" id="product-addtocart-button" class="button btn-cart cssc-button cssc-button--mage" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif;
