<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$_imageHelper = $this->helper('catalog/image');
$_thumbSize = 56;
$_imageSize = 500;
$_zoomSize = 1024;
$_images = array();
$_imagesGallery = $this->getGalleryImages();
$is_galleryMode = (count($_imagesGallery) > 0);

/* Main Image details */
$_productImage = (string)$this->helper('catalog/image')->init($_product, 'image')->resize($_imageSize);
$_productImageAlt = $this->escapeHtml($this->getImageLabel());

/* Gallery image details */
if ($is_galleryMode) {
    $i = 0;
    foreach ($_imagesGallery as $_image):
        $_imageInfo = array(
            'imageUrl' => (string)$_imageHelper->init($this->getProduct() , 'image', $_image->getFile())->resize($_imageSize) ,
            'imageZoomUrl' => (string)$_imageHelper->init($this->getProduct() , 'image', $_image->getFile())->resize($_zoomSize) ,
            'imageThumbUrl' => (string)$_imageHelper->init($this->getProduct() , 'thumbnail', $_image->getFile())->resize($_thumbSize) ,
            'imageAlt' => $this->escapeHtml($_image->getLabel()) ,
        );
        $_imageInfo['isCurrentImage'] = ($_imageInfo['imageUrl'] == $_productImage);
        $_images[$i++] = $_imageInfo;
    endforeach;
}

if ($is_galleryMode): ?>
    <ul class="more-views">
    <?php foreach ($_images as $i => $_image): ?>
        <li>
            <a data-i="<?php echo $i; ?>" target="_blank" href="<?php echo $_image['imageUrl']; ?>" class="<?php echo ($_image['isCurrentImage'] ? 'current' : ''); ?>">
                <img src="<?php echo $_image['imageThumbUrl']; ?>" width="<?php echo $_thumbSize; ?>" height="<?php echo $_thumbSize; ?>" alt="<?php echo $_image['imageAlt']; ?>" />
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
    <div class="product-image-list">
        <?php foreach ($_images as $i => $_image): ?>
        <div data-i="<?php echo $i; ?>" class="product-image <?php echo ($_image['isCurrentImage'] ? 'current' : ''); ?>">
            <img src="<?php echo $_image['imageUrl']; ?>" width="<?php echo $_imageSize; ?>" height="<?php echo $_imageSize; ?>" alt="<?php echo $_image['imageAlt']; ?>" />
        </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="product-image">
        <img src="<?php echo $_productImage; ?>" width="<?php echo $_imageSize; ?>" height="<?php echo $_imageSize; ?>" alt="<?php echo $_productImageAlt; ?>" />
    </div>
<?php endif; ?>