<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
$_sendToFriendModel = Mage::registry('send_to_friend_model');
$_canSendToFriend = ($_sendToFriendModel && $_sendToFriendModel->canEmailToFriend());

/* Metas */
$_product_name = urlencode($_helper->productAttribute($_product, $_product->getName(), 'name'));
$_product_url = urlencode($_product->getProductUrl());
$_product_image = urlencode($this->helper('catalog/image')->init($_product, 'small_image')->resize(200));

/* Methods */
$_methods = array(
    'twitter' => array(
        'name' => 'Twitter',
        'url' => 'https://twitter.com/home?status='.$_product_name.'+'.$_product_url
    ),
    'facebook' => array(
        'name' => 'Facebook',
        'url' => 'https://www.facebook.com/sharer/sharer.php?u='.$_product_url
    ),
    'pinterest' => array(
        'name' => 'Pinterest',
        'url' => 'https://pinterest.com/pin/create/button/?url='.$_product_url.'&media='.$_product_image.'&description='.$_product_name
    ),
    'googleplus' => array(
        'name' => 'Google Plus',
        'url' => 'https://plus.google.com/share?url='.$_product_url
    ),
    'email' => array(
        'name' => 'Email',
        'url' => str_replace('+', '%20','mailto:mail@mail.com?subject='.$_product_name.'&body='.$_product_name.'+'.$_product_url)
    )
);

if ($_canSendToFriend):
    $_methods['email']['url'] = $this->helper('catalog/product')->getEmailToFriendUrl($_product);
endif;

?>
<div class="product-share">
    <h3><?php echo $this->__('Share this product'); ?></h3>
    <ul class="share-list">
        <?php foreach ($_methods as $_id => $_method) { ?>
        <li><a target="_blank" href="<?php echo $_method['url']; ?>" class="<?php echo $_id; ?>"><?php echo $_method['name']; ?></a></li>
        <?php } ?>
    </ul>
</div>
