<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

/** @var $this Mage_Sales_Block_Order_Info */
$_order = $this->getOrder();
$_links = $this->getLinks();
echo $this->getMessagesBlock()->getGroupedHtml();
?>
<div class="page-title">
    <h1 class="main-title"><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>

<?php if(count($_links) > 1): ?>
<ul id="order-info-tabs">
<?php foreach ($_links as $_link): ?>
    <?php if($_link->getUrl()): ?>
        <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
    <?php else: ?>
        <li class="current"><?php echo $_link->getLabel() ?></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<ul>
    <li><h3><?php echo $this->__('Order Date:') ?></h3> <?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long'); ?></li>
    <li><h3><?php echo $this->__('Payment Method:') ?></h3> <?php echo $this->getPaymentInfoHtml() ?></li>
    <?php if (!$_order->getIsVirtual()): ?>
    <li>
        <h3><?php echo $this->__('Shipping Method') ?></h3>
        <?php if ($_order->getShippingDescription()): ?>
            <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        <?php else: ?>
            <?php echo $this->helper('sales')->__('No shipping information available'); ?>
        <?php endif; ?>
    </li>
    <?php endif; ?>

</ul>

<p class="order-date"></p>

<?php if (!$_order->getIsVirtual()): ?>
<div class="box-account">
    <h2><?php echo $this->__('Shipping Address') ?></h2>
    <div class="item-address">
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
</div>
<?php endif; ?>

<div class="box-account">
    <h2><?php echo $this->__('Billing Address') ?></h2>
    <div class="item-address">
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
</div>


