<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2 class="account-subtitle"><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table account-table recent-orders-table" id="my-orders-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th class="mobile-hide"><?php echo $this->__('Ship To') ?></th>
                <th><?php echo $this->__('Order Total') ?></th>
                <th><?php echo $this->__('Status') ?></th>
                <th class="mobile-hide">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
                    <td><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></td>
                    <td class="mobile-hide"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td><?php echo $_order->getStatusLabel() ?></td>
                    <td class="mobile-hide"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
