<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2015 Darklg
 * @license     MIT
 */
$_h = $this->helper('krr_cmstools');
$_page = $_h->getPage();
?>
<div class="cms-layout">
    <h1 class="cms-layout__title"><?php echo $_page['title']; ?></h1>
    <div class="cms-layout__content"><?php echo $_page['content']; ?></div>
</div>
