<?php
/**
 * Magento : Base styleguide page
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

/* ----------------------------------------------------------
  CRUMBS
---------------------------------------------------------- */
?>
<div class="breadcrumbs">
    <ul>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="home">
            <a itemprop="url" href="#" title="Aller à la page d'accueil">
                <span itemprop="title">Accueil</span>
            </a>
        </li>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="cms_page">
            <strong itemprop="title">Styleguide</strong>
        </li>
    </ul>
</div>

<?php
/* ----------------------------------------------------------
  Page Title
---------------------------------------------------------- */
?>
<div class="page-title">
    <h1>Styleguide</h1>
</div>

<?php
/* ----------------------------------------------------------
  CMS Content
---------------------------------------------------------- */
?>
<h1>CMS Content</h1>
<div class="std">
    <h2>Liste de citations</h2>
    <h3>Various quotes</h3>
    <p>For me, I am driven by two main philosophies, know more today about the world than I knew yesterday. And along the way, lessen the suffering of others. You'd be surprised how far that gets you. <a href="/">Neil deGrasse Tyson</a>. History does not repeat itself, but it does rhyme. <em>Mark Twain</em>.</p>
    <p>Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves. <em>A. Einstein.</em> <img src="http://placehold.it/16x16" alt="" /> When I am abroad, I always make it a rule never to criticize or attack the government of my own country. I make up for lost time when I come home. <strong>Winston Churchill.</strong></p>
    <h4>Other cool quotes</h4>
    <p>A hundredth of a second here, a hundredth of a second there - even if you put them end to end, they still only add up to one, two, perhaps three seconds, snatched from eternity. <a href="#">Robert Doisneau.</a> All I know is what the words know, and dead things, and that makes a handsome little sum, with a beginning and a middle and an end, as in the well-built phrase and the long sonata of the dead. <strong>Samuel Beckett.</strong></p>
    <p>And this, our life, exempt from public haunt, finds tongues in trees, books in the running brooks, sermons in stones, and good in everything. <a href="#"><strong>William Shakespeare.</strong></a></p>
    <h3>Abraham Lincoln</h3>
    <ul>
        <li>A friend is one who has the same enemies as you have. </li>
        <li>Am I not destroying my enemies when I make friends of them? </li>
        <li>Any people anywhere, being inclined and having the power, have the right to rise up, and shake off the existing government, and form a new one that suits them better. <img src="http://placehold.it/16x16" alt="" /> This is a most valuable - a most sacred right - a right, which we hope and believe, is to liberate the world. </li>
        <li>Be sure you put your feet in the right place, then stand firm. </li>
    </ul>
    <blockquote><p>The world needs dreamers and the world needs doers. But above all, the world needs dreamers who do — Sarah Ban Breathnach.</p></blockquote>
    <h3>Martin Luther King, Jr</h3>
    <ul>
        <li>A man can't ride your back unless it's bent.</li>
        <li>Take the first step in faith.
            <ul>
                <li>You don't have to see the whole staircase :</li>
                <li>just take the first step.</li>
            </ul>
        </li>
        <li>A genuine leader is not a searcher for consensus but a molder of consensus.</li>
    </ul>
    <table>
        <thead>
            <tr>
                <th>Title 1</th>
                <th>Title 2</th>
                <th>Title 3</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Data 1</td>
                <td>Data 2</td>
                <td>Data 3</td>
            </tr>
            <tr>
                <td>Data 3</td>
                <td>Data 4 </td>
                <td>Data 4</td>
            </tr>
        </tbody>
    </table>
    <p>thiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolongthiswordistoolong</p>
</div>

<?php
/* ----------------------------------------------------------
  Forms
---------------------------------------------------------- */
?>
<h1>Forms</h1>
<form action="#" method="post">
    <div class="fieldset">
        <h2 class="legend">Personal Information</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name-prefix">
                    <div class="field name-prefix">
                        <label for="prefix" class="required">
                            <em>*</em>
                            Prefix
                        </label>
                        <div class="input-box">
                            <input id="prefixMadame" type="radio" value="Madame" name="prefix">
                            <label for="prefixMadame">Madame</label>
                            <input id="prefixMonsieur" type="radio" value="Monsieur" name="prefix">
                            <label for="prefixMonsieur">Monsieur</label>
                        </div>
                    </div>
                    <div class="field name-firstname">
                        <label for="firstname" class="required">
                            <em>*</em>
                            First Name
                        </label>
                        <div class="input-box">
                            <input type="text" id="firstname" name="firstname" value="" title="First Name" maxlength="255" class="input-text required-entry" data-com.agilebits.onepassword.user-edited="yes">
                        </div>
                    </div>
                    <div class="field name-lastname">
                        <label for="lastname" class="required">
                            <em>*</em>
                            Last Name
                        </label>
                        <div class="input-box">
                            <input type="text" id="lastname" name="lastname" value="" title="Last Name" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <label for="email_address" class="required">
                    <em>*</em>
                    Email Address
                </label>
                <div class="input-box">
                    <input type="text" name="email" id="email_address" value="" title="Email Address" class="input-text validate-email required-entry">
                </div>
            </li>
            <li class="control">
                <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox">
                <label for="is_subscribed">Sign Up for Newsletter</label>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="zip" class="required">
                        <em>*</em>
                        Zip/Postal Code
                    </label>
                    <div class="input-box">
                        <input type="text" name="postcode" value="" title="Zip/Postal Code" id="zip" class="input-text validate-zip-international required-entry sanitize-zip-FR">
                    </div>
                </div>
                <div class="field">
                    <label for="country" class="required">
                        <em>*</em>
                        Country
                    </label>
                    <div class="input-box">
                        <select name="country_id" id="country" class="validate-select" title="Country">
                            <option value="">
                            </option>
                            <option value="FR" selected="selected">France</option>
                        </select>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <p class="back-link"><a href="#"><small>« </small>Back</a></p>
        <button data-action="save-customer-address" type="submit" title="Save Address" class="button button--secondary"><span><span>Remove Address</span></span></button>
        <button data-action="save-customer-address" type="submit" title="Save Address" class="button"><span><span>Save Address</span></span></button>
    </div>
</form>


<?php
/* ----------------------------------------------------------
  Tables
---------------------------------------------------------- */
?>
<h1>Tables</h1>
<h2>Product table</h2>
<p>Cart / Success / Sales</p>
<table class="product-table--base">
    <thead>
        <tr>
            <th>Column name</th>
            <th>Column name</th>
            <th>Column name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
    </tbody>
</table>

<h2>Data table</h2>
<p>Customer Account</p>
<table class="data-table--base">
    <thead>
        <tr>
            <th>Column name</th>
            <th>Column name</th>
            <th>Column name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
    </tbody>
</table>

<?php
/* ----------------------------------------------------------
  Various
---------------------------------------------------------- */
?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
