<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="save_and_share" title="<?php echo $this->__('Share Wishlist') ?>" class="button btn-share cssc-button cssc-button--mage"><?php echo $this->__('Share Wishlist') ?></button>
<?php endif;
