<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div class="block block-subscribe">
    <h3 class="block-title"><?php echo $this->__('Newsletter') ?></h3>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
        <div class="form-append">
            <div class="input-box">
                <input type="email" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text inputbase required-entry validate-email" />
            </div>
            <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="cssc-button cssc-button--mage"><?php echo $this->__('Subscribe') ?></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>