<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
/* @var $this Mage_Sendfriend_Block_Send */
/**
 * Send to friend form
 *
 * @see Mage_Sendfriend_Block_Send
 */
?>
<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
    function remove_recipient(i){
        $('recipients_name'+i).up(3).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI")),
        ul_mail = Element.extend(document.createElement("UL"));
        li_mail.addClassName('fields additional-row');
        ul_mail.innerHTML = '<li class="box"><label for="recipients_name'+i+'" class="required"><?php echo $this->jsQuoteEscape($this->__('Name:')) ?> <em>*<\/em><\/label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/li>';
        ul_mail.innerHTML += '<li class="box"><label for="recipients_email'+i+'" class="required"><?php echo $this->jsQuoteEscape($this->__('Email Address:')) ?> <em>*<\/em><\/label><div class="input-box"><input name="recipients[email][]" value="" title="<?php echo $this->jsQuoteEscape($this->__('Email Address')) ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/li>';
        ul_mail.innerHTML += '<li class="box"><small><a href="delete_email" title="<?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?><\/a></small><\/li>'
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
        }

        li_mail.appendChild(ul_mail);
        ul.appendChild(li_mail);
    }
//]]>
</script>

<div class="send-friend">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="page-title">
        <h1 class="main-title"><?php echo $this->__('Email to a Friend') ?></h1>
    </div>
    <form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <h2 class="legend"><?php echo $this->__('Sender:') ?></h2>
            <ul class="cssc-form float-form cssc-form--mage" id="sender_options">
                <li class="box">
                    <label for="sender_name" class="required"><?php echo $this->__('Name:') ?> <em>*</em></label>
                    <div class="input-box">
                        <input name="sender[name]" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" title="<?php echo $this->__('Name') ?>" id="sender_name" type="text" class="input-text required-entry" />
                    </div>
                </li>
                <li class="box">
                   <label for="sender_email" class="required"><?php echo $this->__('Email:') ?> <em>*</em></label>
                   <div class="input-box">
                       <input name="sender[email]" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" id="sender_email" type="text" class="input-text required-entry validate-email" />
                   </div>
                </li>
                <li class="box">
                    <label for="sender_message" class="required"><?php echo $this->__('Message:') ?> <em>*</em></label>
                    <div class="input-box">
                        <textarea name="sender[message]" class="input-text required-entry" id="sender_message" cols="3" rows="3"><?php echo $this->escapeHtml($this->getMessage())?></textarea>
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Recipient:') ?></h2>
            <ul class="cssc-form float-form cssc-form--mage" id="recipients_options">
                <li class="box">
                    <label for="recipients_name" class="required"><?php echo $this->__('Name:') ?> <em>*</em></label>
                    <div class="input-box">
                        <input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" />
                    </div>
                </li>
                <li class="box">
                    <label for="recipients_email" class="required"><?php echo $this->__('Email Address:') ?> <em>*</em></label>
                    <div class="input-box">
                        <input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email" type="text" class="input-text required-entry validate-email" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <div id="max_recipient_message" style="display:none;">
                <?php if ($this->getMaxRecipients()): ?>
                  <p class="limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
                <?php endif; ?>
            </div>
            <p>
            <button type="submit" class="cssc-button cssc-button--mage button<?php if (!$this->canSend()):?> disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><?php echo $this->__('Send Email') ?></button>
            <?php if (1 < $this->getMaxRecipients()): ?>
                <button id="add_recipient_button" type="button" onclick="add_recipient();" class="cssc-button cssc-button--mage button"><?php echo $this->__('Add Recipient') ?></button>
            <?php endif; ?>
            </p>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
        productSendtofriendForm.submit = function() {
            if(this.validator.validate()) {
                this.form.submit();
            }
        }.bind(productSendtofriendForm);
    //]]>
    </script>
</div>
