<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
$_sortDirections = array(
    'asc' => 'ascending',
    'desc' => 'descending'
);
if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <div class="pager">
        <?php echo $this->getPagerHtml() ?>
    </div>

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
        <?php /*
<!-- Text version -->
<?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
    <?php foreach($_sortDirections as $dir => $dirName): ?>
    <a href="<?php echo $this->getOrderUrl($_key, $dir) ?>"<?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == $dir): ?> class="current"<?php endif; ?>><?php echo $this->__($_order. ' ' . $dirName) ?></a>
    <?php endforeach; ?>
<?php endforeach; ?>

         */ ?>
    </div>
    <?php endif; ?>
</div>
<?php endif;
