<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-title title-buttons">
    <h1 class="main-title"><?php echo $this->__('Address Book') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<p>
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="cssc-button cssc-button--default" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add New Address') ?></button>
</p>
<div class="addresses-primary">
    <h2><?php echo $this->__('Default Addresses') ?></h2>
    <ol>
        <li class="item-address">
            <h3><?php echo $this->__('Default Billing Address') ?></h3>
            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <address><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></address>
            <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
            <?php else: ?>
            <p><?php echo $this->__('You have no default billing address in your address book.') ?></p>
            <?php endif ?>
        </li>
        <li class="item-address">
            <h3><?php echo $this->__('Default Shipping Address') ?></h3>
            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <address>
                <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
            </address>
            <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
            <?php else: ?>
            <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            <?php endif ?>
        </li>
    </ol>
</div>
<div class="addresses-additional">
    <h2><?php echo $this->__('Additional Address Entries') ?></h2>
    <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
    <ol>
        <?php foreach($_pAddsses as $_address): ?>
        <li class="item-address">
            <address>
                <?php echo $this->getAddressHtml($_address) ?>
            </address>
            <p>
                <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a><br />
                <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>
            </p>
        </li>
        <?php endforeach; ?>
    </ol>
    <?php else: ?>
        <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
    <?php endif ?>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
