<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
echo $this->getMessagesBlock()->toHtml();
?>
<div class="addresses-list">
    <h2><?php echo $this->__('Address Book') ?></h2>
    <div class="buttons-set">
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add New Address')) ?>" class="button" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
    </div>
    <div class="addresses-primary">
        <h2><?php echo $this->__('Default Addresses') ?></h2>
        <ol class="col2-set col2-set--base col2-set--customer">
        <li class="col-1">
            <div class="item item--address">
            <h3><?php echo $this->__('Default Billing Address') ?></h3>
            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <address>
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                    <br /><a class="button" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
                </address>
            <?php else: ?>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            <?php endif ?>
            </div>
        </li>
        <li class="col-2">
            <div class="item item--address">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                    <address>
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                        <br />
                        <a class="button" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Edit') ?></a>
                    </address>
                <?php else: ?>
                    <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                <?php endif ?>
            </div>
        </li>
        </ol>
    </div>
    <div class="addresses-additional">
        <h2><?php echo $this->__('Additional Address Entries') ?></h2>
        <ol>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
            <li>
                <div class="item item--address">
                    <address>
                        <?php echo $this->getAddressHtml($_address) ?>
                        <br /><a class="button" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit') ?></a>
                        <br /><a href="#" class="button button--secondary link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete') ?></a>
                    </address>
                </div>
            </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li class="empty">
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
            </li>
        <?php endif ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to delete this address?')) ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
