<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <header class="page-title">
        <h1 class="main-title"><?php echo $this->__('Shopping Cart') ?></h1>
    </header>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <table id="shopping-cart-table" class="data-table cart-table">
            <?php foreach($this->getItems() as $_item): ?>
                <?php echo $this->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
    </form>

    <?php
    echo $this->getChildHtml('checkout.cart.extra');
    echo $this->getChildHtml('coupon');
    echo $this->getChildHtml('totals');
    ?>

    <div class="cart-buttons">
    <?php
    if($this->getContinueShoppingUrl()):
        ?><button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="cssc-button cssc-button--mage btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><?php echo $this->__('Continue Shopping') ?></button><?php
    endif;
    if(!$this->hasError()):
        foreach ($this->getMethods('methods') as $method):
            if ($methodHtml = $this->getMethodHtml($method)):
                echo $methodHtml;
            endif;
        endforeach;
    endif;
    ?>
    </div>
</div>
