<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

$_columns = $this->getColumns();
if (count($this->getItems())): ?>
<div id="wishlist-table" class="wishlist-items">
    <?php foreach ($this->getItems() as $_item): ?>
        <div class="item-wishlist" id="item_<?php echo $_item->getId();?>">
        <?php
        foreach ($_columns as $_column):
            $_column->setItem($_item);
            echo $_column->toHtml($_item);
        endforeach;
        ?>
        </div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<p class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></p>
<?php endif; ?>
<?php foreach ($_columns as $_column): ?>
    <?php echo $_column->getAdditionalHtml();?>
<?php endforeach; ?>
<script type="text/javascript">
//<![CDATA[
<?php foreach ($_columns as $_column):
    echo $_column->getJs();
endforeach; ?>
//]]>
</script>
