<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

$columns = $this->getColumns();
if (count($this->getItems())): ?>
<div id="wishlist-table" class="wishlist-items">
    <?php foreach ($this->getItems() as $item): ?>
        <div class="item-wishlist" id="item_<?php echo $item->getId();?>">
        <?php
        foreach ($columns as $column):
            $column->setItem($item);
            echo $column->toHtml($item);
        endforeach;
        ?>
        </div>
    <?php endforeach; ?>
</div>
<?php else: ?>
<p class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></p>
<?php endif; ?>
<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml();?>
<?php endforeach; ?>
<script type="text/javascript">
//<![CDATA[
<?php foreach ($columns as $column): ?>
    <?php echo $column->getJs();?>
<?php endforeach; ?>
//]]>
</script>
