<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */
$_links = $this->getLinks();
?>
<ul class="menu-account hide-on-mobile">
    <?php foreach ($_links as $_link): ?>
        <li <?php if ($this->isActive($_link)) { echo ' class="current"'; } ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
    <?php endforeach; ?>
</ul>
<select class="hide-on-desktop" name="menu-account" id="menu-account" onchange="window.location.href=this.value;return false;">
<?php foreach ($_links as $_link): ?>
    <option <?php if ($this->isActive($_link)) { echo ' selected="selected"'; } ?> value="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></option>
<?php endforeach; ?>
</select>
