<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

$_store = Mage::app()->getStore();
$_lang = substr(Mage::app()->getLocale()->getLocaleCode(), 0, 2);
$_siteName = trim(Mage::app()->getWebsite()->getName());
$_siteUrl = $this->getUrl('', array(
    '_nosid' => true,
    '_query' => 'utm_campaign=email_transac&utm_medium=email&utm_source=email_transac&utm_content=email_transac'
));
$_bgColor = '#f0f0f0';
$_pageWidth = 600;
$_marginWidth = 10;
?><!DOCTYPE HTML>
<html lang="<?php echo $_lang; ?>">
<head>
<meta charset="<?php echo Mage::getStoreConfig('design/head/default_charset'); ?>" />
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo Mage::getStoreConfig('design/head/default_charset'); ?>" />
<style type="text/css">
body {}
html,body{width:100%!important;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;margin:0;padding:0;font-family:sans-serif;}
img{text-align:center;color:#000;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;height:auto;max-width:100%}
.nobr{white-space:nowrap;}
.ReadMsgBody{width:100%;}
.ExternalClass{width:100%;}
span.yshortcuts{color:#000;background-color:none;border:none;}
span.yshortcuts:hover,
span.yshortcuts:active,
span.yshortcuts:focus{color:#000;background-color:none;border:none;}
p{margin:0 0 10px;}
.itg-mail-wrapper.itg-mail-wrapper a,
a{-webkit-transition: all 0.3s ease;transition: all 0.3s ease;text-decoration:none;color:#000;}
.itg-mail-wrapper.itg-mail-wrapper a:hover,
.itg-mail-wrapper.itg-mail-wrapper a:focus,
a:hover,a:focus{color: #336699;}
</style>
<title><?php echo $_siteName; ?></title>
<?php /* https://www.emailonacid.com/blog/article/email-development/ensure_that_your_entire_email_is_rendered_by_default_in_the_iphone_ipad */;?>
<!-- 1019 Chars for mobile mail bug <?php for ($i = 0; $i < 1019; $i++) {echo '-';}?> -->
</head>
<body style="padding:0;margin:0;background-color:<?php echo $_bgColor; ?>;">
<div class="itg-mail-wrapper" style="padding:0;background-color:<?php echo $_bgColor; ?>;">
<table border="0" cellspacing="0" cellpadding="0" align="center" width="100%" style="background-color:<?php echo $_bgColor; ?>;">
<tr><td height="20"></td></tr>
<tr><td align="center">
<table border="0" cellspacing="0" cellpadding="0" width="600" style="background-color:#FFFFFF;">
<?php /* Main Container start */;?>
<tr><td colspan="3" height="20"></td></tr>
<tr><td colspan="3" style="text-align:center" align="center"><a href="<?php echo $_siteUrl; ?>"><img src="<?php echo $this->getSkinUrl('images/logo-email.png'); ?>" alt="<?php echo htmlentities($_siteName); ?>" /></a></td></tr>
<tr><td colspan="3" height="<?php echo $_marginWidth; ?>"></td></tr>
<tr><td width="<?php echo $_marginWidth; ?>"></td><td width="<?php echo $_pageWidth-2*$_marginWidth; ?>" align="left" style="font:13px/1.3 sans-serif;">
<?php /* Main Content start */;?>
<?php if($this->getHeadertitle()): ?>
    <h1><?php echo $this->getHeadertitle(); ?></h1>
<?php endif; ?>
