<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<form id="discount-coupon-form" class="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <h2><?php echo $this->__('Discount Codes') ?></h2>
    <div class="discount-form">
        <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
        <input type="hidden" name="remove" id="remove-coupone" value="0" />
        <div class="input-box">
            <input class="input-text inputbase" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
        </div>
        <div class="buttons-set">
            <button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="cssc-button cssc-button--mage" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
            <?php if(strlen($this->getCouponCode())): ?>
                &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="cssc-button cssc-button--mage" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
            <?php endif;?>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
