<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<!DOCTYPE html>
<!--[if lt IE 8 ]><html dir="ltr" lang="fr-FR" class="is_ie7 lt_ie8 lt_ie9 lt_ie10"><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="fr-FR" class="is_ie8 lt_ie9 lt_ie10"><![endif]-->
<!--[if IE 9 ]><html dir="ltr" lang="fr-FR" class="is_ie9 lt_ie10"><![endif]-->
<!--[if gt IE 9]><html dir="ltr" lang="fr-FR" class="is_ie10"><![endif]-->
<!--[if !IE]><!--><html dir="ltr" lang="fr-FR"><!--<![endif]-->
<head>
    <meta charset="UTF-8" />
    <title><?php echo $this->pageTitle; ?></title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="skin/frontend/integento/default/css/main.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl()?>css/styles.css" />
</head>
<body class="magento-errors">
    <?php require_once $contentTemplate; ?>
</body>
</html>