<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
/**
 * Customer onepage checkout login form template
 *
 * @see app/design/frontend/base/default/template/checkout/onepage/login.phtml
 */
/** @var $this Mage_Checkout_Block_Onepage_Login */

echo $this->getChildHtml('login_before')?>
<div class="cssc-grid fluid-grid">
    <div class="col-50p">
        <div class="register-form">
            <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <ul class="form-list">
                    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                    </li>
                    <?php endif; ?>
                    <li class="control">
                        <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                    </li>
                </ul>
            <?php else: ?>
                <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
            <?php endif; ?>
            <div class="buttons-set">
                <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                    <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><?php echo $this->__('Continue') ?></button>
                <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                    <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><?php echo $this->__('Register') ?></button>
                <?php else: ?>
                    <form action="<?php echo $this->getUrl('persistent/index/saveMethod'); ?>">
                        <button id="onepage-guest-register-button" type="submit" class="button"><?php echo $this->__('Register') ?></button>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class="col-50p">
        <div class="login-form">
            <h3><?php echo $this->__('Already registered?') ?></h3>
            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
            <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
            <fieldset>
                <?php echo $this->getBlockHtml('formkey'); ?>
                <p><?php echo $this->__('Please log in below:') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="login-email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="login-password" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>
                        <div class="input-box">
                            <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                        </div>
                    </li>
                    <li>
                        <input name="context" type="hidden" value="checkout" />
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                    </li>
                    <li class="box submit-box">
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button type="submit" class="button" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
                    </li>
                </ul>

            </fieldset>
            </form>
        </div>
    </div>
</div>




<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
<?php
    $registerParam = $this->getRequest()->getParam('register');
    if ($registerParam || $registerParam === ''):
?>
    <script type="text/javascript">
    //<![CDATA[
        document.observe("dom:loaded", function() {
            if($('login:register')) {
                $('login:register').checked = true;
                checkout.setMethod();
            }
        })
    //]]>
    </script>
<?php endif; ?>
