<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) Darklg
 * @license     MIT
 */

$_blockTitle = trim($this->getTitle());
$_h = $this->helper('integento_catalog');

if (($_products = $this->getProductCollection()) && $_products->getSize()):
    if (!empty($_blockTitle)) {
        echo '<h2>' . $_blockTitle . '</h2>';
    }
    echo '<ul class="products-list ig-products-list">';
    foreach ($_products->getItems() as $_product):
        echo '<li>' . $_h->getProductHTML($_product) . '</li>';
    endforeach;
    echo '</ul>';
endif;
