<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
?>
<div class="page-title">
    <h1 class="main-title"><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post" id="customer-resetforgottenpassword-form-validate">
    <div class="fieldset">
        <ul class="cssc-form float-form cssc-form--mage">
            <li class="box">
                <label for="password" class="required"><?php echo $this->__('New Password'); ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                </div>
            </li>
            <li class="box">
                <label for="confirmation" class="required"><?php echo $this->__('Confirm New Password'); ?></label>
                <div class="input-box">
                    <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </li>
            <li class="box submit-box">
                <button type="submit" title="<?php echo $this->__('Reset a Password'); ?>" class="cssc-button cssc-button--mage"><?php echo $this->__('Reset a Password'); ?></button>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('customer-resetforgottenpassword-form-validate', true);
/*]]>*/
</script>
