<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */

$_isLoggedIn = $this->helper('customer')->isLoggedIn();
$_loginPostUrl = Mage::getUrl('customer/account/loginPost');
$_h = $this->helper('customer/data');
?>
<div class="toolbar-element toolbar-element--account wdrw">
    <a href="<?php echo $_h->getAccountUrl(); ?>" class="account">
        <?php echo $this->__('My account'); ?>
    </a>
    <div class="toolbar-element__content submenu submenu-r">
        <?php if($_isLoggedIn) : ?>
            <p><?php echo $this->__('Hello, %s!', $this->escapeHtml($_h->getCustomerName())) ?></p>
            <p><a href="<?php echo $this->getUrl('customer/account/edit'); ?>"><?php echo $this->__('Edit my infos'); ?></a></p>
            <p><a href="<?php echo $_h->getLogoutUrl(); ?>"><?php echo $this->__('Logout'); ?></a></p>
        <?php else: ?>
            <form id="header-login-form" action="<?php echo $_loginPostUrl; ?>" method="post">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <ul class="form-list">
                    <li class="field">
                        <label for="mini-login"><?php echo $this->__('Email:') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" id="mini-login" class="input-text" />
                        </div>
                    </li>
                    <li class="field">
                        <label for="mini-password"><?php echo $this->__('Password:') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" id="mini-password" class="input-text" />
                        </div>
                        <small class="help">
                            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </small>
                    </li>
                    <li class="field login-submit-box">
                        <div class="actions">
                            <button type="submit" class="button"><?php echo $this->__('Login') ?></button>
                        </div>
                    </li>
                </ul>
            </form>
        <?php endif; ?>
    </div>
</div>
