<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
$isLoggedIn = $this->helper('customer')->isLoggedIn();
$loginPostUrl = Mage::getUrl('customer/account/loginPost');
$h = $this->helper('customer/data');
?>
<div class="toolbar-element toolbar-element--account wdrw">
    <a href="<?php echo $h->getAccountUrl(); ?>" class="account">
        <?php echo $this->__('My account'); ?>
    </a>
    <div class="toolbar-element__content submenu submenu-r">
        <?php if($isLoggedIn) : ?>
            <p><?php echo $this->__('Hello, %s!', $this->escapeHtml($h->getCustomerName())) ?></p>
            <p><a href="<?php echo $this->getUrl('customer/account/edit'); ?>"><?php echo $this->__('Edit my infos'); ?></a></p>
            <p><a href="<?php echo $h->getLogoutUrl(); ?>"><?php echo $this->__('Logout'); ?></a></p>
        <?php else: ?>
            <form id="header-login-form" action="<?php echo $loginPostUrl; ?>" method="post">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <ul class="cssc-form cssc-form--default">
                    <li class="box">
                        <label for="mini-login"><?php echo $this->__('Email:') ?></label>
                        <input type="text" name="login[username]" id="mini-login" class="input-text" />
                    </li>
                    <li class="box">
                        <label for="mini-password"><?php echo $this->__('Password:') ?></label>
                        <input type="password" name="login[password]" id="mini-password" class="input-text" />
                        <small class="help">
                            <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </small>
                    </li>
                    <li class="box login-submit-box">
                        <div class="actions">
                            <button type="submit" class="cssc-button cssc-button--default"><?php echo $this->__('Login') ?></button>
                        </div>
                    </li>
                </ul>
            </form>
        <?php endif; ?>
    </div>
</div>