<?php
/**
 * Magento
 *
 * @category    design
 * @package     integento_default
 * @author      Darklg <darklg.blog@gmail.com>
 * @copyright   Copyright (c) 2014 Darklg
 * @license     MIT
 */
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
if(count($this->getStores())>1): ?>
<div class="form-language"><?php
    foreach ($this->getStores() as $_lang):
        $_class = ($_lang->getId() == $this->getCurrentStoreId()) ? ' current' : '';
        ?><a href="<?php echo $_lang->getCurrentUrl() ?>" class="<?php echo $_class; ?>"><?php echo $this->escapeHtml($_lang->getName()) ?></a><?php
    endforeach;
?></div>
<?php endif;